name: create executables
run-name: building executables for commit ${{ github.sha }}
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: bun build --compile --target=bun-windows-x64 main.js --outfile ${{vars.PROJECT_NAME}}-win.exe
      - run: bun build --compile --target=bun-linux-x64 main.js --outfile ${{vars.PROJECT_NAME}}-linux
      - run: bun build --compile --target=bun-darwin-arm64 main.js --outfile ${{vars.PROJECT_NAME}}-osx-arm
      - run: bun build --compile --target=bun-darwin-x64 main.js --outfile ${{vars.PROJECT_NAME}}-osx-x64
      - name: Upload windows-executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: ${{vars.PROJECT_NAME}}-win.exe
      - name: Upload linux-executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: ${{vars.PROJECT_NAME}}-linux
      - name: Upload macos-arm executable
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm-executable
          path: ${{vars.PROJECT_NAME}}-osx-arm
      - name: Upload macos-x64 executable
        uses: actions/upload-artifact@v4
        with:
          name: macos-x64-executable
          path: ${{vars.PROJECT_NAME}}-osx-x64
      - run: mv ${{vars.PROJECT_NAME}}-osx-x64 ${{vars.PROJECT_NAME}}-${{ github.ref_name }}_osx-x64
        if: startsWith(github.ref, 'refs/tags/')
      - run: mv ${{vars.PROJECT_NAME}}-osx-arm ${{vars.PROJECT_NAME}}-${{ github.ref_name }}_osx-arm
        if: startsWith(github.ref, 'refs/tags/')
      - run: mv ${{vars.PROJECT_NAME}}-linux ${{vars.PROJECT_NAME}}-${{ github.ref_name }}_linux
        if: startsWith(github.ref, 'refs/tags/')
      - run: mv ${{vars.PROJECT_NAME}}-win.exe ${{vars.PROJECT_NAME}}-${{ github.ref_name }}_win.exe
        if: startsWith(github.ref, 'refs/tags/')
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{vars.PROJECT_NAME}}_${{  github.ref_name }}_osx-arm
            ${{vars.PROJECT_NAME}}_${{  github.ref_name }}_osx-x64
            ${{vars.PROJECT_NAME}}_${{  github.ref_name }}-linux
            ${{vars.PROJECT_NAME}}_${{  github.ref_name }}-win.exe
