name: create executable
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: bun build --compile --target=bun-windows-x64 main.js --outfile ${{vars.PROJECT_NAME}}.exe
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: ${{vars.PROJECT_NAME}}.exe
